### ISSUE TITLE
Method getMiddleware does not exist.

### ISSUE THREAD

**Issue by iiiyu** [flipboxstudio/lumen-generator#25] opened 2018-01-15 22:10 UTC
I used 
```
"dingo/api": "2.0.0-alpha1"
```
and route/web.php 
```
$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function ($api) {
    $api->get('/test', [
        'as' => 'index',
        'uses' => 'App\Http\Controllers\Controller@getIndex',
    ]);
});
```
When i am executing:
```
php artisan route:list
```
It returns a message:
```
In Macroable.php line 96:

  Method getMiddleware does not exist.
```

**Comment by joelhy** [comment] 2018-01-24 06:23
Are you sure it is caused by Lumen generator?
Maybe you should open an issue in dingo/api.

**Comment by gazben** [comment] 2018-03-08 09:28
@iiiyu I created a pull request to address this issue.

If you add the function the command output will be something like this:
```
+----------+---------------------+--------------+------------------------------------------+------------------+------------------------------+
| Verb     | Path                | NamedRoute   | Controller                               | Action           | Middleware                   |
+----------+---------------------+--------------+------------------------------------------+------------------+------------------------------+
| GET      | /                   |              | App\Http\Controllers\ServerController    | name             |                              |
| GET|HEAD | api/status/ping     |              | App\Http\Controllers\ServerController    | ping             | api.controllers|api.throttle |
| GET|HEAD | api/status/version  |              | App\Http\Controllers\ServerController    | version          | api.controllers|api.throttle |

```

**Comment by thilanga** [comment] 2018-03-08 11:15
PR #1537 has been merged

**Closed as completed** 2018-03-08 11:25 UTC
